In [1]:
import pandas as pd
import os
import urllib
import pdb
import cv2
import numpy as np

In [3]:
shape_label = {'삼각형': 0, '사각형': 1, '오각형': 2, '육각형': 3, '팔각형': 4, 
               '원형': 5, '반원형': 6, '타원형': 7, '장방형': 8, '마름모형': 9, '기타': 10}
shape_label

{'기타': 10,
 '마름모형': 9,
 '반원형': 6,
 '사각형': 1,
 '삼각형': 0,
 '오각형': 2,
 '원형': 5,
 '육각형': 3,
 '장방형': 8,
 '타원형': 7,
 '팔각형': 4}

In [4]:
label_path = './label/label_shape.xls'
xls = pd.read_excel(label_path)
df = pd.DataFrame(xls)
# print(df1)

df2 = df[df.columns[-1]].map(shape_label)
df2 = pd.DataFrame(df2)
df['shape'] = df2['shape']
# df['shape'].astype(str)
# df['No'].astype(str)
print(df)

              No  shape
0      197400571      5
1      198803039      8
2      200703756      5
3      199703153      8
4      200004062      5
5      200402488      5
6      199102043      8
7      199702297      5
8      200502773      7
9      199502505      8
10     200300408      8
11     199700745      8
12     200300405      7
13     198701796      8
14     200202791      5
15     200700055      5
16     198100119      5
17     198700405      8
18     198200170      8
19     200300401      8
20     200200444      7
21     200400462      8
22     200400486      7
23     200400475      8
24     198100123      8
25     200500547      7
26     199400494      5
27     200200445      5
28     199700749      5
29     200500548      7
...          ...    ...
21084  201804334      5
21085  201804348      8
21086  201803560      5
21087  201804952      5
21088  201804850      5
21089  201804185      5
21090  201804849      5
21091  201804347      5
21092  201805299      5
21093  201804353      5
21094  201803800      4
21095  201803829      8
21096  201803515      8
21097  201803392      5
21098  201803666      8
21099  201803679      8
21100  201805040      8
21101  201900219      5
21102  201900303      7
21103  201803530      5
21104  201804162      7
21105  201900304      7
21106  201804719      8
21107  201804256      5
21108  201804443      7
21109  201804675      8
21110  201804837      7
21111  201803835      0
21112  201804625      5
21113  201804159      5

[21114 rows x 2 columns]

In [5]:
df.columns

Index(['No', 'shape'], dtype='object')

In [6]:
df2 = pd.DataFrame(columns=['No','shape'])
df3 = pd.DataFrame(columns=['No','shape'])

In [7]:
img_list = ['197700114.jpg', '197700085.jpg', '197700142.jpg', '197700117.jpg', '197700192.jpg', '197700137.jpg', '197700088.jpg', '197700171.jpg', '197700126.jpg', '197700120.jpg', '195900001.jpg', '196200002.jpg', '195900043.jpg', '196200034.jpg', '196000003.jpg', '195900032.jpg', '196300043.jpg', '196000011.jpg', '196000001.jpg', '196000008.jpg', '196200032.jpg', '196300001.jpg', '196300019.jpg', '196700049.jpg', '196200043.jpg', '196200046.jpg', '196400037.jpg', '196400046.jpg', '196400005.jpg', '196300064.jpg', '196400082.jpg', '196800048.jpg', '196800078.jpg', '196400099.jpg', '196600011.jpg', '196500004.jpg', '196600007.jpg', '196700060.jpg', '196600012.jpg', '196900043.jpg', '197000049.jpg', '197000068.jpg', '197000005.jpg', '197000079.jpg', '197000050.jpg', '197100057.jpg', '197000053.jpg', '196900101.jpg', '197000076.jpg', '197000212.jpg', '197000037.jpg', '197000215.jpg', '197000040.jpg', '197100073.jpg', '197000208.jpg', '197100165.jpg', '197000102.jpg', '197000196.jpg', '197100015.jpg', '197200016.jpg', '197000211.jpg', '197100081.jpg', '197000104.jpg', '197100097.jpg', '197100088.jpg', '197200025.jpg', '197200092.jpg', '197200226.jpg', '197200084.jpg', '197200091.jpg', '197200376.jpg', '197200160.jpg', '197300021.jpg', '197300128.jpg', '197300084.jpg', '197300013.jpg', '197200171.jpg', '197300104.jpg', '197200484.jpg', '197400059.jpg', '197400028.jpg', '197300155.jpg', '197400039.jpg', '197400033.jpg', '197300172.jpg', '197400186.jpg', '197300151.jpg', '197300135.jpg', '197400040.jpg', '197300096.jpg', '197400397.jpg', '197400273.jpg', '197400347.jpg', '197400277.jpg', '197400246.jpg', '197400571.jpg', '197400278.jpg', '197400262.jpg', '197400343.jpg', '197400345.jpg', '197500140.jpg', '197400577.jpg', '197500016.jpg', '197500097.jpg', '197500088.jpg', '197500135.jpg', '197500004.jpg', '197500015.jpg', '197500098.jpg', '197500186.jpg', '197500007.jpg', '197500185.jpg', '197500274.jpg', '197500336.jpg', '197500285.jpg', '197500236.jpg', '197500272.jpg', '197500541.jpg', '197500234.jpg', '197500188.jpg', '197500299.jpg', '197500248.jpg', '197500338.jpg', '197500346.jpg', '197600035.jpg', '197600329.jpg', '197500450.jpg', '197500578.jpg', '197500463.jpg', '197600345.jpg', '197500580.jpg', '197600065.jpg', '197600036.jpg', '197500654.jpg', '197600046.jpg', '197600444.jpg', '197600432.jpg', '197600554.jpg', '197600612.jpg', '197600141.jpg', '197600539.jpg', '197700049.jpg', '197700008.jpg', '197600412.jpg', '197600483.jpg', '197700025.jpg', '197600550.jpg', '197700036.jpg', '197700028.jpg', '197600739.jpg']

In [8]:
for i in range(len(img_list)):
    df3 = df.loc[df['No'] == int(img_list[i].split('.')[0])]
    df2 = df2.append(df3, ignore_index=True)

In [10]:
for i in range(len(df2)):
    df2['shape'][i] = str(df2['shape'][i])
    df2['No'][i] = str(df2['No'][i]) + '.jpg'

In [15]:
df2.to_csv('./test_shape.csv', mode='w')

In [16]:
type(df2['No'][0])

str

In [7]:
# prediction 하고나서 다른 값들만 모아보기

LABEL_PATH = './label'
df = pd.read_csv(os.path.join(LABEL_PATH,'shape_VGG16.csv'))
shape_list = df['shape'].tolist()
pre_list = df['prediction'].tolist()
result = []
for i in range(len(shape_list)):
    if (shape_list[i] != pre_list[i]):
        result.append(i)
print(result)
df2 = pd.DataFrame(columns=['No','shape','prediction'])
for i in range(len(result)):
    df3 = df.loc[df['Unnamed: 0'] == result[i]]
    df2 = df2.append(df3)

df2.to_csv('./pre_shape.csv', mode='w')

In [6]:
label_path = './label/label_shape.xls'
xls = pd.read_excel(label_path)
df = pd.DataFrame(xls)
df

              No shape
0      197400571    원형
1      198803039   장방형
2      200703756    원형
3      199703153   장방형
4      200004062    원형
5      200402488    원형
6      199102043   장방형
7      199702297    원형
8      200502773   타원형
9      199502505   장방형
10     200300408   장방형
11     199700745   장방형
12     200300405   타원형
13     198701796   장방형
14     200202791    원형
15     200700055    원형
16     198100119    원형
17     198700405   장방형
18     198200170   장방형
19     200300401   장방형
20     200200444   타원형
21     200400462   장방형
22     200400486   타원형
23     200400475   장방형
24     198100123   장방형
25     200500547   타원형
26     199400494    원형
27     200200445    원형
28     199700749    원형
29     200500548   타원형
...          ...   ...
21084  201804334    원형
21085  201804348   장방형
21086  201803560    원형
21087  201804952    원형
21088  201804850    원형
21089  201804185    원형
21090  201804849    원형
21091  201804347    원형
21092  201805299    원형
21093  201804353    원형
21094  201803800   팔각형
21095  201803829   장방형
21096  201803515   장방형
21097  201803392    원형
21098  201803666   장방형
21099  201803679   장방형
21100  201805040   장방형
21101  201900219    원형
21102  201900303   타원형
21103  201803530    원형
21104  201804162   타원형
21105  201900304   타원형
21106  201804719   장방형
21107  201804256    원형
21108  201804443   타원형
21109  201804675   장방형
21110  201804837   타원형
21111  201803835   삼각형
21112  201804625    원형
21113  201804159    원형

[21114 rows x 2 columns]

In [5]:
label_path = './label/label_color.xls'
xls = pd.read_excel(label_path)
df = pd.DataFrame(xls)
df

              No color_front
0      197400571          노랑
1      198803039          갈색
2      200703756          분홍
3      199703153          하양
4      200004062          하양
5      200402488          하양
6      199102043          초록
7      199702297          하양
8      200502773          하양
9      199502505          초록
10     200300408          노랑
11     199700745          연두
12     200300405          자주
13     198701796          파랑
14     200202791          하양
15     200700055          하양
16     198100119          하양
17     198700405          연두
18     198200170          하양
19     200300401          하양
20     200200444          주황
21     200400462          갈색
22     200400486          주황
23     200400475          파랑
24     198100123          초록
25     200500547          하양
26     199400494          하양
27     200200445          연두
28     199700749          연두
29     200500548          주황
...          ...         ...
21084  201804334          노랑
21085  201804348          연두
21086  201803560          주황
21087  201804952          하양
21088  201804850          하양
21089  201804185          노랑
21090  201804849          하양
21091  201804347          하양
21092  201805299          하양
21093  201804353          하양
21094  201803800          분홍
21095  201803829          투명
21096  201803515          노랑
21097  201803392          하양
21098  201803666          주황
21099  201803679          파랑
21100  201805040          하양
21101  201900219          하양
21102  201900303          분홍
21103  201803530          노랑
21104  201804162          갈색
21105  201900304          노랑
21106  201804719          하양
21107  201804256          하양
21108  201804443          파랑
21109  201804675          갈색
21110  201804837          갈색
21111  201803835          노랑
21112  201804625          하양
21113  201804159          하양

[21114 rows x 2 columns]

In [39]:
label_path = './label/color.csv'
csv = pd.read_csv(label_path)
df = pd.DataFrame(csv)
df

       Unnamed: 0  index             No  color_front
0               0      0  197400571.jpg          2.0
1               1      1  198803039.jpg         11.0
2               2      2  200703756.jpg          9.0
3               3      3  199703153.jpg         14.0
4               4      4  200004062.jpg         14.0
5               5      5  200402488.jpg         14.0
6               6      6  199102043.jpg          4.0
7               7      7  199702297.jpg         14.0
8               8      8  200502773.jpg         14.0
9               9      9  199502505.jpg          4.0
10             10     10  200300408.jpg          2.0
11             11     11  199700745.jpg          3.0
12             12     12  200300405.jpg         10.0
13             13     13  198701796.jpg          6.0
14             14     14  200202791.jpg         14.0
15             15     15  200700055.jpg         14.0
16             16     16  198100119.jpg         14.0
17             17     17  198700405.jpg          3.0
18             18     18  198200170.jpg         14.0
19             19     19  200300401.jpg         14.0
20             20     20  200200444.jpg          1.0
21             21     21  200400462.jpg         11.0
22             22     22  200400486.jpg          1.0
23             23     23  200400475.jpg          6.0
24             24     24  198100123.jpg          4.0
25             25     25  200500547.jpg         14.0
26             26     26  199400494.jpg         14.0
27             27     27  200200445.jpg          3.0
28             28     28  199700749.jpg          3.0
29             29     29  200500548.jpg          1.0
...           ...    ...            ...          ...
20929       20929  21084  201804334.jpg          2.0
20930       20930  21085  201804348.jpg          3.0
20931       20931  21086  201803560.jpg          1.0
20932       20932  21087  201804952.jpg         14.0
20933       20933  21088  201804850.jpg         14.0
20934       20934  21089  201804185.jpg          2.0
20935       20935  21090  201804849.jpg         14.0
20936       20936  21091  201804347.jpg         14.0
20937       20937  21092  201805299.jpg         14.0
20938       20938  21093  201804353.jpg         14.0
20939       20939  21094  201803800.jpg          9.0
20940       20940  21095  201803829.jpg         15.0
20941       20941  21096  201803515.jpg          2.0
20942       20942  21097  201803392.jpg         14.0
20943       20943  21098  201803666.jpg          1.0
20944       20944  21099  201803679.jpg          6.0
20945       20945  21100  201805040.jpg         14.0
20946       20946  21101  201900219.jpg         14.0
20947       20947  21102  201900303.jpg          9.0
20948       20948  21103  201803530.jpg          2.0
20949       20949  21104  201804162.jpg         11.0
20950       20950  21105  201900304.jpg          2.0
20951       20951  21106  201804719.jpg         14.0
20952       20952  21107  201804256.jpg         14.0
20953       20953  21108  201804443.jpg          6.0
20954       20954  21109  201804675.jpg         11.0
20955       20955  21110  201804837.jpg         11.0
20956       20956  21111  201803835.jpg          2.0
20957       20957  21112  201804625.jpg         14.0
20958       20958  21113  201804159.jpg         14.0

[20959 rows x 4 columns]

In [40]:
for i in range(len(df)):
    df['color_front'][i] = df['color_front'][i].astype(int)
    if i % 100 == 0:
        print(i)

C:\Users\secre\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

0
100
200
300
400
500
600
700
800
900
1000
1100
1200
1300
1400
1500
1600
1700
1800
1900
2000
2100
2200
2300
2400
2500
2600
2700
2800
2900
3000
3100
3200
3300
3400
3500
3600
3700
3800
3900
4000
4100
4200
4300
4400
4500
4600
4700
4800
4900
5000
5100
5200
5300
5400
5500
5600
5700
5800
5900
6000
6100
6200
6300
6400
6500
6600
6700
6800
6900
7000
7100
7200
7300
7400
7500
7600
7700
7800
7900
8000
8100
8200
8300
8400
8500
8600
8700
8800
8900
9000
9100
9200
9300
9400
9500
9600
9700
9800
9900
10000
10100
10200
10300
10400
10500
10600
10700
10800
10900
11000
11100
11200
11300
11400
11500
11600
11700
11800
11900
12000
12100
12200
12300
12400
12500
12600
12700
12800
12900
13000
13100
13200
13300
13400
13500
13600
13700
13800
13900
14000
14100
14200
14300
14400
14500
14600
14700
14800
14900
15000
15100
15200
15300
15400
15500
15600
15700
15800
15900
16000
16100
16200
16300
16400
16500
16600
16700
16800
16900
17000
17100
17200
17300
17400
17500
17600
17700
17800
17900
18000
18100
18200
18300
18400
18500
18600
18700
18800
18900
19000
19100
19200
19300
19400
19500
19600
19700
19800
19900
20000
20100
20200
20300
20400
20500
20600
20700
20800
20900

In [43]:
label_path = './label/shape.csv'
csv = pd.read_csv(label_path)
df2 = pd.DataFrame(csv)
df2

       Unnamed: 0  index             No  shape
0               0      0  197400571.jpg      5
1               1      1  198803039.jpg      8
2               2      2  200703756.jpg      5
3               3      3  199703153.jpg      8
4               4      4  200004062.jpg      5
5               5      5  200402488.jpg      5
6               6      6  199102043.jpg      8
7               7      7  199702297.jpg      5
8               8      8  200502773.jpg      7
9               9      9  199502505.jpg      8
10             10     10  200300408.jpg      8
11             11     11  199700745.jpg      8
12             12     12  200300405.jpg      7
13             13     13  198701796.jpg      8
14             14     14  200202791.jpg      5
15             15     15  200700055.jpg      5
16             16     16  198100119.jpg      5
17             17     17  198700405.jpg      8
18             18     18  198200170.jpg      8
19             19     19  200300401.jpg      8
20             20     20  200200444.jpg      7
21             21     21  200400462.jpg      8
22             22     22  200400486.jpg      7
23             23     23  200400475.jpg      8
24             24     24  198100123.jpg      8
25             25     25  200500547.jpg      7
26             26     26  199400494.jpg      5
27             27     27  200200445.jpg      5
28             28     28  199700749.jpg      5
29             29     29  200500548.jpg      7
...           ...    ...            ...    ...
20929       20929  21084  201804334.jpg      5
20930       20930  21085  201804348.jpg      8
20931       20931  21086  201803560.jpg      5
20932       20932  21087  201804952.jpg      5
20933       20933  21088  201804850.jpg      5
20934       20934  21089  201804185.jpg      5
20935       20935  21090  201804849.jpg      5
20936       20936  21091  201804347.jpg      5
20937       20937  21092  201805299.jpg      5
20938       20938  21093  201804353.jpg      5
20939       20939  21094  201803800.jpg      4
20940       20940  21095  201803829.jpg      8
20941       20941  21096  201803515.jpg      8
20942       20942  21097  201803392.jpg      5
20943       20943  21098  201803666.jpg      8
20944       20944  21099  201803679.jpg      8
20945       20945  21100  201805040.jpg      8
20946       20946  21101  201900219.jpg      5
20947       20947  21102  201900303.jpg      7
20948       20948  21103  201803530.jpg      5
20949       20949  21104  201804162.jpg      7
20950       20950  21105  201900304.jpg      7
20951       20951  21106  201804719.jpg      8
20952       20952  21107  201804256.jpg      5
20953       20953  21108  201804443.jpg      7
20954       20954  21109  201804675.jpg      8
20955       20955  21110  201804837.jpg      7
20956       20956  21111  201803835.jpg      0
20957       20957  21112  201804625.jpg      5
20958       20958  21113  201804159.jpg      5

[20959 rows x 4 columns]

In [44]:
df3 = df2['shape']

In [45]:
df['shape'] = df2['shape']

In [47]:
type(df['shape'][1])

numpy.int64

In [49]:
df.to_csv('./label/shape_color_prediction.csv', mode='w')

In [59]:
LABEL_PATH = './label'
df = pd.read_csv(os.path.join(LABEL_PATH,'shape_color_prediction.csv'))

In [60]:
df.head()

,Unnamed: 0,Unnamed: 0.1,index,No,color_front,shape,color_prediction,shape_prediction
0,0,0,0,197400571.jpg,2,5,2,5
1,1,1,1,198803039.jpg,11,8,11,8
2,2,2,2,200703756.jpg,9,5,9,5
3,3,3,3,199703153.jpg,14,8,14,8
4,4,4,4,200004062.jpg,14,5,14,5

In [53]:
color = df['color_front'][1] == df['color_prediction'][1]

True

In [58]:
count = 0
result = 0
for i in range(len(df)):
#     color = df['color_front'][i] == df['color_prediction'][i]
#     shape = df['shape'][i] == df['shape_prediction']
    if (df['color_front'][i] == df['color_prediction'][i]) and (df['shape'][i] == df['shape_prediction'][i]):
        count += 1
result = count / len(df)        
print('shape, color 둘 다 정답인 경우:', count)
print('전체 데이터 크기:', len(df))
print('결과:', result)

shape, color 둘 다 정답인 경우: 18363
전체 데이터 크기: 20959
결과: 0.8761391287752278

In [61]:
LABEL_PATH = './label'
df = pd.read_csv(os.path.join(LABEL_PATH,'shape_color_prediction.csv'))

AttributeError: 'str' object has no attribute 'astype'